### DISCUSSION TITLE
Questions about project.yml file

### DISCUSSION THREAD

**Discussion by FabioNotaro2001** [NVIDIA/NVFlare#1131] [Q&A] [answered]
Hi, everybody.
I'm new to NVFlare and I'm doing some experiments reading the documentation.
In particular I'm stuck with the section related to the real world Federated Learning (https://nvflare.readthedocs.io/en/main/programming_guide/provisioning_system.html#provisioning).
My next step is to edit the file project.yml in order to describe the infrastructure I want to create, but I have many problems with the edit step.

In fact, if possible, I'd like to create an ephemeral infrastructure by using only one pc (so the clients, server, admin ecc are in local but on different ports) but I don't know what to insert as FQDN in name field into the file.
I'm using the latest version of nvflare.

Thanks in advance for every reply and sorry for every possible error or inaccuracy but I'm simply trying to learn.
P.S. I already know that there's a specific simulation for a local infrastructure but I have already followed it, I need to know if it is possibie to make a local infrastructure in real world example and, if yes, how to set correctly the field names in the project.yml file.
Thanks everybody for the availability, I would also appreciate your examples of edit on this file.

**Comment by YuanTingHsieh** [comment, marked as answer]
Hi @FabioNotaro2001 

Thanks for your interest and question!

Yes, it is possible to have clients, server, admin all in one local machine but run in different processes.

We need to update that page for 2.2.1 that is right.

Let me give you some tips.

First, install NVFlare.
Second, run `nvflare provision` and type `1` for `project.yml for HA mode`

Inside the generated project.yml you will see multiple "participants"
For example:

```
participants:
  # change overseer.example.com to the FQDN of the overseer
  - name: overseer
    type: overseer
    org: nvidia
    protocol: https
    api_root: /api/v1
    port: 8443
  # change example.com to the FQDN of the server
  - name: server1
    type: server
    org: nvidia
    fed_learn_port: 8002
    admin_port: 8003
  - name: server2
    type: server
    org: nvidia
    fed_learn_port: 8102
    admin_port: 8103
  - name: site-1
    type: client
    org: nvidia
  - name: site-2
    type: client
    org: nvidia
  - name: admin@nvidia.com
    type: admin
    org: nvidia
    role: project_admin
```

In the real world deployment, the "name" of the overseer will be "somethingxxx.com" or some FQDN.
The "name" of the server also need to be FQDN.

But for your scenario, let's just use this project.yml as it is.


Then let's run `nvflare provision -p project.yml"

It will generated folders inside "./workspace/example_project/prod_00".

Since "overseer" and "server1" and "server2" can not be resolved by DNS service automatically.
One way to deal with that is add them into `/etc/hosts` (if you are using Ubuntu)
You can just add a new line after localhost.
For example:

```

127.0.0.1 localhost
127.0.0.1 overseer server1 server2

```

After these setups, you need to start overseer in one terminal using
"./overseer/startup/start.sh"

Then in another terminal, you start FL server
"./server1/startup/start.sh"

Then in another terminal, you start FL clients
"./site-1/startup/start.sh"

Finally, you can start admin client to interact with the system:
"./admin@nvidia.com/startup/fl_admin.sh"

Then you can just submit the example jobs and starts to play with this real setup.
