### DISCUSSION TITLE
PROVISION CONFIGURATION

### DISCUSSION THREAD

**Discussion by FabioNotaro2001** [NVIDIA/NVFlare#1349] [Q&A] [answered]
I'd like to execute the hello-pt-tb example in a real world scenario. I have an host, which IP is A, that is the host from which I do the provision and generate the folders for client, admin... and I want it to be the server, and another host, suppose its IP is B, and I want it to be a client.
Now, what do I have to write exactly into the file project.yml in order to compile it exactly?

Because I tried to replace the "server1" word with A but it didn't work. I also tried to let the word "server1" and add a line "A server1" into the file /etc/hosts of the host I want it to be the server, but I didn't solve. As it requires an FQDN, I also tried to use the command hostaname -f in order to get my fqdn, but I got my pc name (I don't know if it is also the fqdn) and also using that it doesn't work. I also specify that client and server are hosts of the same network.
I attach the error I got.
The next step I did was to do the command for provisioning, which generated the folders and then I copied the folder site-1 into the host with B as IP. Then I lunched start.sh from the server (host which IP is A) and it seems to start correctly and then I lunched start.sh from the client (host with IP B) but I get this error that repeats every few seconds:
![Schermata del 2023-02-13 13-01-59](https://user-images.githubusercontent.com/93600518/218457350-153d09fc-1c8d-4789-91cf-91aa9bcf9f89.png)
I precise that I am the administrator only of host with IP A (so the server), so I cannot change /etc/hosts from host with IP B (the client). 

So I think my error is a misconfiguration of that file project.yml, so I wonder to know what is the correct way to compile it or if the error isn't there let me know where is it.

I don't know if it can be useful but I just noticed that server and client don't have the really same version of nvflare: server has 2.2.1rc9, while client has 2.2.5.

Thank you very much!

**Comment by chesterxgchen** [comment]
both server and client should be the same version.

**Comment by YuanTingHsieh** [comment, marked as answer]
Hi @FabioNotaro2001 ,

First, please make sure both machine has the same NVFlare version.
And both of them can run a simple hello-numpy-sag example.

Let's assume I have two machine.
Machine one (server) has ip address "10.110.44.123" (you can use `ip a` to find your machine's ip address in Linux).
Machine two (client) has ip address "10.110.46.456".

Let's just use POC mode for now.
Then you modify the project.yml as follows:

```
participants:
  - name: 10.110.44.123
    type: server
    org: my_org
    fed_learn_port: 8002
    admin_port: 8003
  - name: site-1
    type: client
    org: my_ord
```
And also the overseer agent part:

```
      overseer_agent:
        path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
        overseer_exists: false
        args:
          sp_end_point: 10.110.44.123:8002:8003

```

You need to make sure port 8002 and 8003 is not used by other processes on your server machine.
And you need to make sure if you have firewall, you need to open the ports that you want to use (you can look for `firewall-cmd`)

After those are done, you run nvflare provision.
On the server machine, you just run ./10.110.44.123/start/start.sh to start the server.

You need to copy the client package to client machine.
Then you run ./site-1/start/start.sh on the client machine should just work.
