### DISCUSSION TITLE
Dummy overseer agent

### DISCUSSION THREAD

**Discussion by lyscho** [NVIDIA/NVFlare#893] [Q&A] [answered]
Hi NVFlare Team,

For my FL setup I do not require HA, but with the current NVFlare version it appears that using an Overseer is mandatory:

> Overseer setup is now required in provisioning.
> [https://nvflare.readthedocs.io/en/main/programming_guide/high_availability.html#](https://nvflare.readthedocs.io/en/main/programming_guide/high_availability.html#)

I want to avoid opening another port for the overseer, when I do not need its features. But at the same time I want to keep using the most recent NVFlare version.
So these are my open questions:

1. Is it possible to specify a Dummy Overseer that simply refers to the server, by adapting the provisioning setup in `project.yml`? (I strongly want to avoid customizing the NVFlare library, which would require a custom NVFlare setup on each client.)
2. Would I loose out on other features beyond HA by using a Dummy Overseer?

Thank you already!

**Comment by YuanTingHsieh** [comment, marked as answer]
Hi @lyscho thanks for the question!

1. Yes, you sure can use the dummy overseer agent in this case. so you can change these lines: https://github.com/NVIDIA/NVFlare/blob/dev/nvflare/lighter/project.yml#L88-L95 to
```
      overseer_agent:
        path: nvflare.ha.dummy_overseer_agent.DummyOverseerAgent
        # if overseer_exists is true, args here are ignored.  Provisioning
        #   tool will fill role, name and other local parameters automatically.
        # if overseer_exists is false, args in this section will be used.
        overseer_exists: false
        args:
           sp_end_point: [server host name]:[server fl port]:[server admin port]
```

2. No, all other features should be there.

@IsaacYangSLA @yanchengnv please correct me if I am wrong.

Thanks.
