### ISSUE TITLE
[Question] Is client equivalent tenant? 

### ISSUE THREAD

**Issue by Jeffwan** [NVIDIA/NVFlare#1115]
in this example, we have two clients - `site-1` and `site-2`. What's the relationship between clients and tenants and what's the best practice? If one of the client have many resources. Does it mean we need to create multiple clients or there's a way to run multiple copies using same scrips generated for this tenant? 

```
participants:
  # change example.com to the FQDN of the server
  - name: server1
    type: server
    org: nvidia
    fed_learn_port: 8002
    admin_port: 8003
  - name: site-1
    type: client
    org: nvidia
  - name: site-2
    type: client
    org: nvidia
  - name: admin@nvidia.com
    type: admin
    org: nvidia
    role: project_admin
```
