### ISSUE TITLE
OSError: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by drixterOfficial** [NVIDIA/NVFlare#2105]
**Describe the bug**
When running sh start.sh in server startup folder there is a error that is showing. 

From what I think is because I deploy already a server before and now I'm deploying a new server.
Please help, Thank you.

![Screenshot from 2023-10-27 23-06-14](https://github.com/NVIDIA/NVFlare/assets/121430424/7e3d633d-f7b1-4032-b91e-eaa4a4869860)

**Desktop (please complete the following information):**
 - OS:  ubuntu 20.04
 - Python Version 3.10
 - NVFlare Version: 2.3.8

**Comment by YuanTingHsieh** [comment]
@drixterOfficial thanks for your interest!

To deploy another server, you need to modify the "project.yml" file so that the new server takes different ports (since the old server already running and occupying the ports).

And then do the provision again.

project1.yml:
```
participants:
  - name: server1
    type: server
    org: hello
    fed_learn_port: 8002
    admin_port: 8003
```

project2.yml:
```
participants:
  - name: server1
    type: server
    org: hello
    fed_learn_port: 8004
    admin_port: 8005
```

After that you should be able to start a new server without any problem.
